image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

variables:
    TEST_IMAGE: registry.gitlab.com/rpienaar/webapp:$CI_COMMIT_REF_NAME
    
stages:
    - build
    
build:
    stage: build
    script:
        - docker build --pull -t $TEST_IMAGE .
        - docker push $TEST_IMAGE
