image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

variables:
    TEST_IMAGE: registry.gitlab.com/rpienaar/webapp:$CI_COMMIT_REF_NAME
    
stages:
    - build
    - test
    - check
    
build:
    stage: build
    script:
        - ls -la
        - docker info
        - docker build -t $TEST_IMAGE .
        - docker push $TEST_IMAGE

eunit:
    stage: test
    script:
        - docker pull $TEST_IMAGE
        - docker run $TEST_IMAGE /root/webapp/rebar3 eunit -v

common_test:
    stage: test
    script:
        - docker pull $TEST_IMAGE
        - docker run $TEST_IMAGE /root/webapp/run_ct.sh

dialyzer:
    stage: check
    script:
        - docker pull $TEST_IMAGE
        - docker run $TEST_IMAGE /root/webapp/rebar3 dialyzer

xref:
    stage: check
    script:
        - docker pull $TEST_IMAGE
        - docker run $TEST_IMAGE /root/webapp/rebar3 xref